# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67aaa9268970b959bd6a38324861a5225e6564a1d116616bd728d6ee6bd40225f75e3fa3d65c440d82be20a1dc35474eaf2870e5d4c975094d3eb86c5228dbb8

test:
  secret_key_base: 2cf8e55b9ad3458585527264d06270c09b28be24659e53c968be88655f9f536c17e9005e62023a47d683b7f38b45f1449cc6f10890047c9413250036b9c1c101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
